/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0x9QIemNydj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function createfile() {
  return (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle>Create New File</CardTitle>
        <CardDescription>Enter a name for your new file below to get started.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="fileName">File Name</Label>
          <Input id="fileName" placeholder="Enter file name" />
        </div>
      </CardContent>
      <CardFooter className="flex justify-end">
        <Button type="submit">Create File</Button>
      </CardFooter>
    </Card>
  )
}
