/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/UWiJr1kCEnK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export default function signup() {
  return (
    <div className="flex min-h-[100dvh] items-center justify-center bg-[#f0fff4] px-4 py-12 sm:px-6 lg:px-8">
    <div className="w-full max-w-md space-y-6">
      <div className="text-center">
        <h1 className="text-3xl font-bold tracking-tight text-foreground">Sign up to your account</h1>

      </div>
      <Card>
        <CardContent className="space-y-4">
          <div className=" mt-1"><Button variant="outline" className="w-full flex gap-1">
            <ChromeIcon  />
            Sign up with Google
          </Button></div>


          <div className="relative">
            <div className="absolute inset-0 flex items-center">
              <span className="w-full border-t border-muted" />
            </div>
            <div className="relative flex justify-center text-xs uppercase">
              <span className="bg-[#f0fff4] px-2 text-muted-foreground">Or continue with</span>
            </div>
          </div>
          <form className="space-y-4">
            <div>
              <Label htmlFor="email">Email</Label>
              <Input id="email" type="email" placeholder="name@example.com" required />
            </div>
            <div>
              <Label htmlFor="password">Password</Label>
              <Input id="password" type="password" required />
            </div>
            <Link href='/dashboard'>
            <Button type="submit" className="w-full">
              Sign up
            </Button>
            </Link>
          </form>
          <div className="text-center text-sm text-muted-foreground">
            <Link href="/forgot" className="font-medium text-primary hover:underline" prefetch={false}>
              Forgot your password?
            </Link>
          </div>
        </CardContent>
      </Card>
    </div>
  </div>
)
}

function ChromeIcon() {
return (
  <svg

    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <circle cx="12" cy="12" r="10" />
    <circle cx="12" cy="12" r="4" />
    <line x1="21.17" x2="12" y1="8" y2="8" />
    <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
    <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
  </svg>
)
}
