/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tgsAh0rrhIG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Card, CardHeader, CardContent } from "@/components/ui/card"


export default function dashboard() {

  return (
    <div className="flex flex-col min-h-screen bg-muted/40">
      <header className="sticky top-0 z-30 flex items-center h-16 px-4 border-b bg-background sm:px-6">
        <div className="flex items-center gap-4">
          <Button size="sm" className="hidden sm:inline-flex">
            <PlusIcon className="w-4 h-4 mr-2" />
            Create New File
          </Button>
          <div className="relative flex-1 hidden sm:flex">
            <div className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
            <Input type="search" placeholder="Search files..." className="w-full pl-10 rounded-md bg-muted" />
          </div>
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" size="icon" className="ml-auto">
              <img
                src="/placeholder.svg"
                width={36}
                height={36}
                alt="Avatar"
                className="rounded-full"
                style={{ aspectRatio: "36/36", objectFit: "cover" }}
              />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuLabel>My Account</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Settings</DropdownMenuItem>
            <DropdownMenuItem>Support</DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Logout</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </header>
      <main className="flex-1 p-4 sm:p-6 bg-[#f0fff4]">
        <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
          <Card className="transition-transform duration-200 hover:scale-105">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div className="font-medium">Spreadsheet.xlsx</div>
              </div>
            </CardHeader>
            <CardContent className="flex items-center justify-between">
              <div className="text-sm text-muted-foreground">1.5 MB</div>
              <div className="flex items-center gap-2">
                <Button size="icon" variant="ghost">
                  <DownloadIcon className="w-5 h-5" />
                </Button>
                <Button size="icon" variant="ghost">
                  <MoveVerticalIcon className="w-5 h-5" />
                </Button>
              </div>
            </CardContent>
          </Card>
          <Card className="transition-transform duration-200 hover:scale-105">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div className="font-medium">Spreadsheet.xlsx</div>

              </div>
            </CardHeader>
            <CardContent className="flex items-center justify-between">
              <div className="text-sm text-muted-foreground">1.5 MB</div>
              <div className="flex items-center gap-2">
                <Button size="icon" variant="ghost">
                  <DownloadIcon className="w-5 h-5" />
                </Button>
                <Button size="icon" variant="ghost">
                  <MoveVerticalIcon className="w-5 h-5" />
                </Button>
              </div>
            </CardContent>
          </Card>
          <Card className="transition-transform duration-200 hover:scale-105">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div className="font-medium">Spreadsheet.xlsx</div>

              </div>
            </CardHeader>
            <CardContent className="flex items-center justify-between">
              <div className="text-sm text-muted-foreground">1.5 MB</div>
              <div className="flex items-center gap-2">
                <Button size="icon" variant="ghost">
                  <DownloadIcon className="w-5 h-5" />
                </Button>
                <Button size="icon" variant="ghost">
                  <MoveVerticalIcon className="w-5 h-5" />
                </Button>
              </div>
            </CardContent>
          </Card>
          <Card className="transition-transform duration-200 hover:scale-105">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div className="font-medium">Spreadsheet.xlsx</div>

              </div>
            </CardHeader>
            <CardContent className="flex items-center justify-between">
              <div className="text-sm text-muted-foreground">1.5 MB</div>
              <div className="flex items-center gap-2">
                <Button size="icon" variant="ghost">
                  <DownloadIcon className="w-5 h-5" />
                </Button>
                <Button size="icon" variant="ghost">
                  <MoveVerticalIcon className="w-5 h-5" />
                </Button>
              </div>
            </CardContent>
          </Card>
          <Card className="transition-transform duration-200 hover:scale-105">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div className="font-medium">Spreadsheet.xlsx</div>

              </div>
            </CardHeader>
            <CardContent className="flex items-center justify-between">
              <div className="text-sm text-muted-foreground">1.5 MB</div>
              <div className="flex items-center gap-2">
                <Button size="icon" variant="ghost">
                  <DownloadIcon className="w-5 h-5" />
                </Button>
                <Button size="icon" variant="ghost">
                  <MoveVerticalIcon className="w-5 h-5" />
                </Button>
              </div>
            </CardContent>
          </Card>
          <Card className="transition-transform duration-200 hover:scale-105">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div className="font-medium">Spreadsheet.xlsx</div>

              </div>
            </CardHeader>
            <CardContent className="flex items-center justify-between">
              <div className="text-sm text-muted-foreground">1.5 MB</div>
              <div className="flex items-center gap-2">
                <Button size="icon" variant="ghost">
                  <DownloadIcon className="w-5 h-5" />
                </Button>
                <Button size="icon" variant="ghost">
                  <MoveVerticalIcon className="w-5 h-5" />
                </Button>
              </div>
            </CardContent>
          </Card>
          <Card className="transition-transform duration-200 hover:scale-105">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div className="font-medium">Spreadsheet.xlsx</div>

              </div>
            </CardHeader>
            <CardContent className="flex items-center justify-between">
              <div className="text-sm text-muted-foreground">1.5 MB</div>
              <div className="flex items-center gap-2">
                <Button size="icon" variant="ghost">
                  <DownloadIcon className="w-5 h-5" />
                </Button>
                <Button size="icon" variant="ghost">
                  <MoveVerticalIcon className="w-5 h-5" />
                </Button>
              </div>
            </CardContent>
          </Card>
          <Card className="transition-transform duration-200 hover:scale-105">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div className="font-medium">Spreadsheet.xlsx</div>

              </div>
            </CardHeader>
            <CardContent className="flex items-center justify-between">
              <div className="text-sm text-muted-foreground">1.5 MB</div>
              <div className="flex items-center gap-2">
                <Button size="icon" variant="ghost">
                  <DownloadIcon className="w-5 h-5" />
                </Button>
                <Button size="icon" variant="ghost">
                  <MoveVerticalIcon className="w-5 h-5" />
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}

function DownloadIcon() {
  return (
    <svg

      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" x2="12" y1="15" y2="3" />
    </svg>
  )
}


function MoveVerticalIcon() {
  return (
    <svg

      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="8 18 12 22 16 18" />
      <polyline points="8 6 12 2 16 6" />
      <line x1="12" x2="12" y1="2" y2="22" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
